### ISSUE TITLE
Why should we shift the left-top coordinate for one pixel ?

### ISSUE THREAD

**Issue by Beanocean** [Tony607/voc2coco#7]
https://github.com/Tony607/voc2coco/blob/207f265dfc4afaae0dda229b8c27a91ab7e0494a/voc2coco.py#L108-L109

I know the `height` or `width` should be:
```
height = ymax - ymin + 1 = (ymax - (ymin -1))
```

Why we update the `xmin` and `ymin` by minus one? Is this because of the indexing system in python is start from zero?

**Comment by chAwater** [comment]
Yes, according to the VOC2012 Development Kit [(pdf in pjreddie's mirror)](https://pjreddie.com/media/files/VOC2012_doc.pdf):
> The bbox field specifies the bounding box of the object in the image, as
[left,top,right,bottom]. The top-left pixel in the image has coordinates
(1; 1).

**Comment by Beanocean** [comment]
@chAwater Thanks for your explain
